apiVersion: v1
kind: Service
metadata:
  name: {{ include "ready-rag-for-line-chart.fullname" . }}
spec:
  type: {{ .Values.service.type | default "NodePort" }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
      protocol: TCP
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    app: {{ include "ready-rag-for-line-chart.name" . }}
